export const players = {
    easy: [
        { name: "Cristiano Ronaldo", nationality: "Portugal", image: "/players/Ronaldo.jpg" },
        { name: "Lionel Messi", nationality: "Argentina", image: "/players/Messi.jpg" },
        { name: "Neymar Jr", nationality: "Brazil", image: "/players/Neymar.jpg" },
        { name: "Mohamed Salah", nationality: "Egypt", image: "/players/Salah.jpg" },
        { name: "Kylian Mbappe", nationality: "France", image: "/players/Mbappe.jpg" },
        { name: "Kevin De Bruyne", nationality: "Belgium", image: "/players/De_Bruyne.jpg" },
        { name: "Harry Kane", nationality: "England", image: "/players/Kane.jpg" },
        { name: "Virgil van Dijk", nationality: "Netherlands", image: "/players/Van_Dijk.jpg" },
        { name: "Sergio Ramos", nationality: "Spain", image: "/players/Ramos.jpg" },
        { name: "Luka Modrić", nationality: "Croatia", image: "/players/Modric.jpg" },
        { name: "Eden Hazard", nationality: "Belgium", image: "/players/Hazard.jpg" },
        { name: "Robert Lewandowski", nationality: "Poland", image: "/players/Lewandowski.jpg" },
        { name: "Thibaut Courtois", nationality: "Belgium", image: "/players/Courtois.jpg" },
        { name: "Paul Pogba", nationality: "France", image: "/players/Pogba.jpg" },
        { name: "Raheem Sterling", nationality: "England", image: "/players/Sterling.jpg" }
    ],
    medium: [
        { name: "Timo Werner", nationality: "Germany", image: "/players/Werner.jpg" },
        { name: "Richarlison", nationality: "Brazil", image: "/players/Richarlison.jpg" },
        { name: "Joao Felix", nationality: "Portugal", image: "/players/Felix.jpeg" },
        { name: "Jadon Sancho", nationality: "England", image: "/players/Sancho.jpg" },
        { name: "Phil Foden", nationality: "England", image: "/players/Foden.jpg" },
        { name: "Mason Mount", nationality: "England", image: "/players/Mount.jpg" },
        { name: "Ferran Torres", nationality: "Spain", image: "/players/Ferran.jpg" },
        { name: "Gareth Bale", nationality: "Wales", image: "/players/Bale.jpg" },
        { name: "Hector Bellerín", nationality: "Spain", image: "/players/Bellerin.jpeg" },
        { name: "Marco Reus", nationality: "Germany", image: "/players/Reus.jpg" },
        { name: "Ciro Immobile", nationality: "Italy", image: "/players/Immobile.jpg" },
        { name: "Diogo Jota", nationality: "Portugal", image: "/players/Jota.jpg" },
        { name: "Olivier Giroud", nationality: "France", image: "/players/Giroud.jpg" },
        { name: "Bukayo Saka", nationality: "England", image: "/players/Saka.jpg" },
        { name: "Christian Pulisic", nationality: "USA", image: "/players/Pulisic.jpg" }
    ],
    hard: [
        { name: "Andrej Kramarić", nationality: "Croatia", image: "/players/Kramaric.jpg" },
        { name: "Pablo Fornals", nationality: "Spain", image: "/players/Fornals.jpg" },
        { name: "Joshua Kimmich", nationality: "Germany", image: "/players/Kimmich.jpg" },
        { name: "Cédric Soares", nationality: "Portugal", image: "/players/Soares.jpg" },
        { name: "Denis Suárez", nationality: "Spain", image: "/players/Denis.jpg" },
        { name: "Marcos Acuna", nationality: "Argentina", image: "/players/Acuna.jpg" },
        { name: "Youssef En-Nesyri", nationality: "Morocco", image: "/players/EnNesyri.jpg" },
        { name: "Kamil Glik", nationality: "Poland", image: "/players/Glik.jpg" },
        { name: "Jose Luis Gaya", nationality: "Spain", image: "/players/Gaya.jpg" },
        { name: "Alexandre Lacazette", nationality: "France", image: "/players/Lacazette.jpg" },
        { name: "Gerard Moreno", nationality: "Spain", image: "/players/Moreno.jpg" },
        { name: "Nabil Fekir", nationality: "France", image: "/players/Fekir.jpg" },
        { name: "Gonzalo Higuain", nationality: "Argentina", image: "/players/Higuain.jpg" },
        { name: "Moussa Dembele", nationality: "France", image: "/players/Dembele.jpg" },
        { name: "Renato Sanches", nationality: "Portugal", image: "/players/Sanches.jpg" }
    ]
};
